# @package _group_

name: 'LPR'

lr: 0.0005
tau: 0.0025

activation: lrelu
norm: None

lambda_weight_l2: 0.000001
lambda_trans_qreg: 1.0
lambda_rot_qreg: 1.0

rotation_resolution: 5

# Voxel
image_crop_size: 64
bounds_offset: [0.1]
voxel_sizes: [16, 16]

crop_augmentation: True

demo_augmentation: True
demo_augmentation_every_n: 10
exploration_strategy: gaussian

trajectory_lr: 0.001
trajectory_tau: 0.01
trajectory_point_noise: 0.1
trajectory_points: 10
trajectory_samples: 100
trajectory_mode: 'joint'

learn_trajectory_pi: True
