rlbench:
    task: take_lid_off_saucepan
    demos: 10
    demo_path: /my/demo/path
    episode_length: 10
    cameras: [front]
    camera_resolution: [128, 128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]

replay:
    batch_size: 128
    timesteps: 1
    prioritisation: True
    use_disk: False
    path: '/tmp/arm/replay'  # Only used when use_disk is True.

framework:
    log_freq: 100
    train_envs: 1
    eval_envs: 1
    replay_ratio: 128
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 40000
    gpu: 0
    env_gpu: 0
    logdir: '/tmp/arm_test/'
    seeds: 1

defaults:
    - method: C2FARM

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task}/${method.name}
